name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: galeksandrp/openwrt:docker-ci
      options: -u root

    steps:
    - name: sudo install
      run: apk add --update sudo

    - uses: actions/checkout@v2
    - run: mv $GITHUB_WORKSPACE/.git ~/github-workspace-git
    - run: rm -rf $GITHUB_WORKSPACE && mv /home/ng/openwrt $GITHUB_WORKSPACE
    - run: mv ~/github-workspace-git $GITHUB_WORKSPACE/.git

    - name: git diff
      run: git diff --name-status

    - name: git reset
      run: bash -c 'git checkout $(git diff --name-only)'
    - name: git clean
      run: git clean -fd
    - name: cleanup galeksandrp_packages
      run: rm -rf feeds/galeksandrp_packages*

    - name: feeds update
      run: ./scripts/feeds update -a
    - name: feeds install
      run: ./scripts/feeds install -a
    - name: feeds uninstall
      run: ./scripts/feeds uninstall dawn luci-theme-openwrt
    - name: feeds install -p packages
      run: ./scripts/feeds install -p galeksandrp_packages dawn
    - name: feeds install -p luci
      run: ./scripts/feeds install -p galeksandrp_luci luci-theme-openwrt
    - name: diffconfig
      run: cp diffconfig .config
    - name: make defconfig
      run: make defconfig

    - name: diffconfig.sh
      run: ./scripts/diffconfig.sh > diffconfig
    - name: config diff
      run: git diff

    - name: chown
      run: chown ng:ng -R $GITHUB_WORKSPACE
    - name: make
      run: sudo -u ng make -j$(nproc)

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ax3600
        path: |
          bin/targets/ipq807x/generic
          !bin/targets/ipq807x/generic/packages
